#!/usr/bin/env bash
#Using what you did in the previous exercise, write a Bash script that groups visitors by IP a nd HTTP status code, and displays this data.
file="apache-access.log"
awk -F' ' '{ print $1, $9}' $file
