#!/usr/bin/env bash
#Bash script that displays Best School 10 times,but for the 9th iteration,displays Best School and then Hi on a new line.
w=1
while [ $w -le 10 ]
do
    echo "Best School"
    if [ $w -eq 9 ]
    then
        echo "Hi"
    fi
    ((w++))
done
