#!/usr/bin/env bash
# Bash script that loops from 1 to 10 
r=1
while [ $r -le 10 ]
do
    if [ $r -eq 4 ]; then
        echo "bad luck"
    elif [ $r -eq 8 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((r++))
done
