#!/usr/bin/env bash
#Using your previous exercise command, write a Bash script that displays lines containing the #bash word, thus allowing you to easily get the PID of your Bash process
#You cannot use pgrep
#The third line of your script must be # shellcheck disable=SC2009 (for more info about ignori#ng shellcheck error here)

ps -p 4404 -o comm=
# shellcheck disable=SC2009
